In [2]:
import pandas as pd

df = pd.read_csv("ipl_data.csv")

In [3]:
df.head()

,Match_ID,Team,Opponent,Season,Matches_Played,Wins,Losses,Run_Rate,Points,Venue
0,101,CSK,MI,2024,14,9.0,5,8.75,18,Chennai
1,102,MI,CSK,2024,14,8.0,6,8.20,16,Mumbai
2,103,RCB,KKR,2024,14,7.0,7,7.85,14,Bengaluru
3,104,SRH,CSK,2024,14,8.0,6,9.50,16,Hyderabad
4,105,CSK,MI,2024,14,9.0,5,8.75,18,Chennai

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Match_ID        10 non-null     int64
 1   Team            10 non-null     str
 2   Opponent        10 non-null     str
 3   Season          10 non-null     str
 4   Matches_Played  10 non-null     str
 5   Wins            9 non-null      float64
 6   Losses          10 non-null     int64
 7   Run_Rate        9 non-null      float64
 8   Points          10 non-null     int64
 9   Venue           10 non-null     str
dtypes: float64(2), int64(3), str(5)
memory usage: 932.0 bytes

In [5]:
df.columns

Index(['Match_ID', 'Team', 'Opponent', 'Season', 'Matches_Played', 'Wins',
       'Losses', 'Run_Rate', 'Points', 'Venue'],
      dtype='str')

In [6]:
df.describe()

        Match_ID       Wins     Losses   Run_Rate     Points
count   10.00000   9.000000  10.000000   9.000000  10.000000
mean   105.50000   8.777778   5.400000  12.461111  17.200000
std      3.02765   4.409586   4.195235  12.519055   8.390471
min    101.00000   5.000000  -6.000000   7.200000  10.000000
25%    103.25000   7.000000   5.250000   8.000000  14.000000
50%    105.50000   8.000000   6.500000   8.200000  15.000000
75%    107.75000   9.000000   7.000000   8.750000  17.500000
max    110.00000  20.000000   9.000000  45.800000  40.000000

In [7]:
df.isnull().sum()

Match_ID          0
Team              0
Opponent          0
Season            0
Matches_Played    0
Wins              1
Losses            0
Run_Rate          1
Points            0
Venue             0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [10]:
df["Team"] = df["Team"].str.strip().str.title()

In [11]:
df

,Match_ID,Team,Opponent,Season,Matches_Played,Wins,Losses,Run_Rate,Points,Venue
0,101,Csk,MI,2024,14,9.0,5,8.75,18,Chennai
1,102,Mi,CSK,2024,14,8.0,6,8.20,16,Mumbai
2,103,Rcb,KKR,2024,14,7.0,7,7.85,14,Bengaluru
3,104,Srh,CSK,2024,14,8.0,6,9.50,16,Hyderabad
4,105,Csk,MI,2024,14,9.0,5,8.75,18,Chennai
5,106,Gt,RR,2024,14,NaN,7,8.10,14,Ahmedabad
6,107,Pbks,DC,2024,14,6.0,8,NaN,12,Chandigarh
7,108,Delhi Capitals,LSG,2024,14,20.0,-6,45.80,40,Delhi
8,109,Mi,KKR,twenty24,14,7.0,7,8.00,14,Mumbai
9,110,Rr,SRH,2024,abc,5.0,9,7.20,10,Jaipur

In [12]:
df["Season"] = pd.to_datetime(df["Season"], errors="coerce")

In [13]:
df

,Match_ID,Team,Opponent,Season,Matches_Played,Wins,Losses,Run_Rate,Points,Venue
0,101,Csk,MI,2024-01-01,14,9.0,5,8.75,18,Chennai
1,102,Mi,CSK,2024-01-01,14,8.0,6,8.20,16,Mumbai
2,103,Rcb,KKR,2024-01-01,14,7.0,7,7.85,14,Bengaluru
3,104,Srh,CSK,2024-01-01,14,8.0,6,9.50,16,Hyderabad
4,105,Csk,MI,2024-01-01,14,9.0,5,8.75,18,Chennai
5,106,Gt,RR,2024-01-01,14,NaN,7,8.10,14,Ahmedabad
6,107,Pbks,DC,2024-01-01,14,6.0,8,NaN,12,Chandigarh
7,108,Delhi Capitals,LSG,2024-01-01,14,20.0,-6,45.80,40,Delhi
8,109,Mi,KKR,NaT,14,7.0,7,8.00,14,Mumbai
9,110,Rr,SRH,2024-01-01,abc,5.0,9,7.20,10,Jaipur

In [14]:
df["Season"].dtype

dtype('<M8[us]')

In [15]:
df[df.duplicated()]

Empty DataFrame
Columns: [Match_ID, Team, Opponent, Season, Matches_Played, Wins, Losses, Run_Rate, Points, Venue]
Index: []

In [16]:
df = df.drop_duplicates()

In [17]:
df.shape

(10, 10)

In [18]:
df["Matches_Played"] = pd.to_numeric(
    df["Matches_Played"], errors="coerce"
)

In [19]:
df

,Match_ID,Team,Opponent,Season,Matches_Played,Wins,Losses,Run_Rate,Points,Venue
0,101,Csk,MI,2024-01-01,14.0,9.0,5,8.75,18,Chennai
1,102,Mi,CSK,2024-01-01,14.0,8.0,6,8.20,16,Mumbai
2,103,Rcb,KKR,2024-01-01,14.0,7.0,7,7.85,14,Bengaluru
3,104,Srh,CSK,2024-01-01,14.0,8.0,6,9.50,16,Hyderabad
4,105,Csk,MI,2024-01-01,14.0,9.0,5,8.75,18,Chennai
5,106,Gt,RR,2024-01-01,14.0,NaN,7,8.10,14,Ahmedabad
6,107,Pbks,DC,2024-01-01,14.0,6.0,8,NaN,12,Chandigarh
7,108,Delhi Capitals,LSG,2024-01-01,14.0,20.0,-6,45.80,40,Delhi
8,109,Mi,KKR,NaT,14.0,7.0,7,8.00,14,Mumbai
9,110,Rr,SRH,2024-01-01,NaN,5.0,9,7.20,10,Jaipur

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Match_ID        10 non-null     int64
 1   Team            10 non-null     str
 2   Opponent        10 non-null     str
 3   Season          9 non-null      datetime64[us]
 4   Matches_Played  9 non-null      float64
 5   Wins            9 non-null      float64
 6   Losses          10 non-null     int64
 7   Run_Rate        9 non-null      float64
 8   Points          10 non-null     int64
 9   Venue           10 non-null     str
dtypes: datetime64[us](1), float64(3), int64(3), str(3)
memory usage: 932.0 bytes