In [1]:
import pandas as pd

df = pd.read_csv("ipl_fan_store_ecommerce.csv")

In [2]:
df.head()

,Order_ID,Product,Category,Quantity,Unit_Price_INR,Total_Amount_INR,City,Payment_Method,Order_Status,Order_Date
0,1001,MI Jersey,Apparel,2.0,1499.0,2998.0,Mumbai,UPI,Delivered,2026-04-12
1,1002,MI Cap,Accessories,1.0,599.0,599.0,Pune,Card,Delivered,2026-04-13
2,1003,MI Jersey,Apparel,2.0,1499.0,2998.0,Mumbai,UPI,Delivered,2026-04-12
3,1004,MI Flag,Fan Merchandise,3.0,299.0,897.0,Navi Mumbai,Cash,Shipped,2026-04-15
4,1005,MI Mug,Home & Living,1.0,NaN,399.0,Thane,UPI,Processing,2026-04-16

In [3]:
df.shape

(10, 10)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          10 non-null     int64
 1   Product           10 non-null     str
 2   Category          10 non-null     str
 3   Quantity          9 non-null      float64
 4   Unit_Price_INR    9 non-null      float64
 5   Total_Amount_INR  9 non-null      float64
 6   City              10 non-null     str
 7   Payment_Method    10 non-null     str
 8   Order_Status      10 non-null     str
 9   Order_Date        10 non-null     str
dtypes: float64(3), int64(1), str(6)
memory usage: 932.0 bytes

In [5]:
df.isnull().sum()

Order_ID            0
Product             0
Category            0
Quantity            1
Unit_Price_INR      1
Total_Amount_INR    1
City                0
Payment_Method      0
Order_Status        0
Order_Date          0
dtype: int64

In [6]:
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())

df["Unit_Price_INR"] = df["Unit_Price_INR"].fillna(
    df["Unit_Price_INR"].median()
)

df["Total_Amount_INR"] = df["Total_Amount_INR"].fillna(
    df["Total_Amount_INR"].median()
)

In [7]:
df

,Order_ID,Product,Category,Quantity,Unit_Price_INR,Total_Amount_INR,City,Payment_Method,Order_Status,Order_Date
0,1001,MI Jersey,Apparel,2.0,1499.0,2998.0,Mumbai,UPI,Delivered,2026-04-12
1,1002,MI Cap,Accessories,1.0,599.0,599.0,Pune,Card,Delivered,2026-04-13
2,1003,MI Jersey,Apparel,2.0,1499.0,2998.0,Mumbai,UPI,Delivered,2026-04-12
3,1004,MI Flag,Fan Merchandise,3.0,299.0,897.0,Navi Mumbai,Cash,Shipped,2026-04-15
4,1005,MI Mug,Home & Living,1.0,1499.0,399.0,Thane,UPI,Processing,2026-04-16
5,1006,MI Hoodie,Apparel,1.0,2199.0,2199.0,Mumbai,Card,Delivered,2026-04-17
6,1007,MI Keychain,Accessories,4.0,199.0,1499.0,Pune,UPI,Delivered,2026-04-18
7,1008,MI Jersey,apparel,1.0,1499.0,1499.0,Mumbai,UPI,Delivered,2026-04-19
8,1009,MI Signed Bat,Collectibles,1.0,999999.0,999999.0,Delhi,Card,Delivered,2026-04-20
9,1010,MI Socks,Apparel,-2.0,249.0,-498.0,Chennai,UPI,Delivered,not-a-date

In [8]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df = df.drop_duplicates()

In [11]:
df["Product"] = df["Product"].str.strip().str.title()
df["Category"] = df["Category"].str.strip().str.title()
df["City"] = df["City"].str.strip().str.title()
df["Payment_Method"] = df["Payment_Method"].str.strip().str.title()
df["Order_Status"] = df["Order_Status"].str.strip().str.title()

In [12]:
df

,Order_ID,Product,Category,Quantity,Unit_Price_INR,Total_Amount_INR,City,Payment_Method,Order_Status,Order_Date
0,1001,Mi Jersey,Apparel,2.0,1499.0,2998.0,Mumbai,Upi,Delivered,2026-04-12
1,1002,Mi Cap,Accessories,1.0,599.0,599.0,Pune,Card,Delivered,2026-04-13
2,1003,Mi Jersey,Apparel,2.0,1499.0,2998.0,Mumbai,Upi,Delivered,2026-04-12
3,1004,Mi Flag,Fan Merchandise,3.0,299.0,897.0,Navi Mumbai,Cash,Shipped,2026-04-15
4,1005,Mi Mug,Home & Living,1.0,1499.0,399.0,Thane,Upi,Processing,2026-04-16
5,1006,Mi Hoodie,Apparel,1.0,2199.0,2199.0,Mumbai,Card,Delivered,2026-04-17
6,1007,Mi Keychain,Accessories,4.0,199.0,1499.0,Pune,Upi,Delivered,2026-04-18
7,1008,Mi Jersey,Apparel,1.0,1499.0,1499.0,Mumbai,Upi,Delivered,2026-04-19
8,1009,Mi Signed Bat,Collectibles,1.0,999999.0,999999.0,Delhi,Card,Delivered,2026-04-20
9,1010,Mi Socks,Apparel,-2.0,249.0,-498.0,Chennai,Upi,Delivered,not-a-date